### ISSUE TITLE
Homebridge (MacOS issue)

### ISSUE THREAD

**Issue by cavvy-mike** [homebridge-plugins/homebridge-philips-air#125]
Hi i have Philips Air Purifier AC3036/10. The CoAP protocol was in my case (http and plain CoAP are not able to set up the connection. 

I do not have a possibility to use Automode or Sleepmode or turbomede with HomeKit App. There are two Fan speeds (Speed 1 and Speed 2) possible. Any idea how to fix that?

Best Regards
cavvy-mike

**Comment by Sunoo** [comment]
They should be supported, auto/manual is a toggle below fan speed, and turbo is achieved but turning the fan speed all the way up.
